topkecleon/otouto

plugins/imdb.lua

imdapi doesn't work. Replaced by omdbapi

Fixed imdb API link.

---

plugins/youtube.lua

Adding youtube plugin

---

README.md

Add new plugin in the list:
-nick
-wikipedia
-spotify
-youtube
-translate
Even more. :D

Add new plugin in README

---

README.md

Organization of command list of plugins:
- Added new plugins on list
- Listed a-z ~ 1-0
:D

Organization of command list of plugins

---

plugins/chatter.lua

- Change in location of response: (res.msg)

Fix bug - Plugin chatter.lua

---

plugins/gImages.lua

Fix Google Search Images

---

README.md
config.lua
plugins/apod.lua

Gets Astronomy Picture of the Day, from NASA.

Added APOD plugin.

---

plugins/librefm.lua

Add librefm plugin

---

plugins/youtube.lua

- Fix message erro to "no results found."
- Removed fixed result.

Improvements to Youtube

---

plugins/apod.lua

new commands:
/apod
/apodhd
/apodtext

Improved apod.lua

---

plugins/apod.lua
plugins/reddit.lua

Solved Message "Connection error."

Solved "Connection error."

---

config.lua
plugins/chatter.lua

Update to support the new API
INFO:
Get key: http://developer.simsimi.com/signUp
If the license is not a "trial" = `simsimi_trial = false`

New API for Simsimi

---

.gitignore

FIX .gitignore
Linus Torvalds - didn't like that :)

FIX .gitignore

---

config.lua
plugins/translate.lua

Why use?
- Google doesn't work (New API paid)
- 1,000,000 characters per day but not more than 10,000,000 per month.
- Free :D 
Get Key https://tech.yandex.com/keys/get/?service=trnsl
Doc https://tech.yandex.com/translate/doc/dg/reference/translate-docpage/

Migrating to yandex (translate)

---

bindings.lua

Also fixed send Voice and send Video

Added disable_notification

---

plugins/administration.lua

FIX cli_port

---

README.md

Add url for google cse: https://cse.google.com/cse :)

Add url for google cse

---

README.md

README Update references

---

bindings.lua

Add sendVenue:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/topkecleon/otouto/52)

Add sendVenue

---

plugins/about.lua
plugins/bandersnatch.lua
plugins/bible.lua
plugins/calc.lua
plugins/chatter.lua
plugins/commit.lua
plugins/currency.lua
plugins/echo.lua
plugins/eightball.lua
plugins/fortune.lua
plugins/gImages.lua
plugins/gMaps.lua
plugins/hackernews.lua
plugins/imdb.lua
plugins/lastfm.lua
plugins/librefm.lua
plugins/nick.lua
plugins/patterns.lua
plugins/ping.lua
plugins/remind.lua
plugins/time.lua
plugins/translate.lua
plugins/weather.lua

Improvements and fix

---

otouto/plugins/shout.lua
otouto/utilities.lua

- Fix issue #66
- Regex moved to `utilities.char.utf_8`
- ~~New limit is 17 char. (Reason: Break line)~~

Fix and improvement in shout

---

otouto/plugins/pokemon-go.lua
otouto/utilities.lua

There's more to add later probably, but at least we won't be pinning polls all the time.

Add Pokémon Go plugin.

---

otouto/plugins/administration.lua
otouto/utilities.lua

The branch could have been better named, looking back at it. I don't like the `i` duplication, but it's worth it for usability in tighter loops on the interpreter, esp. in a helper function where it's not taking up space in the middle of unrelated stuff.

Better antisquig

---

otouto/plugins/administration.lua
otouto/utilities.lua

Revert "Better antisquig"

---

otouto/plugins/ping.lua

So what if I told you I was a cute girl
(Regression in d7ecf9e)

Fix an important regression in ping.lua

---

otouto/plugins/administration.lua
otouto/utilities.lua

I don't know how I could mess this up, but I'm tired and I have a tendency to do that with everything. Also, take 4 on avoiding horrible Unicode characters in source by using the thing we even set up a backport library for

[2×cop emoji] fun police time, no more empty names

---

otouto/plugins/currency.lua

PR: Update currency convertor API address

---

otouto/plugins/disable_plugins.lua

You'll probably just want to hit rebase instead of merge for this.

Patch #99 because Lua

---

otouto/plugins/core/blacklist.fnl

The saga continues. Hopefully, this will be the final conversion PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/topkecleon/otouto/111)

[WIP] By your powers combined, merge adminstration and master
